<template>
  <LoginPage
    v-if="!user"
    v-model:login-pin="loginPin"
    :is-supabase-configured="isSupabaseConfigured"
    :login-users="loginUsers"
    :selected-login-user-id="selectedLoginUserId"
    :loading="loading"
    :selected-login-user="selectedLoginUser"
    :session-status="sessionStatus"
    :status="status"
    :avatar-options="avatarOptions"
    :sanitize-pin="sanitizePin"
    :on-select-login-user="selectLoginUser"
    :on-login="handleLogin"
  />

  <AppShell
    v-else
    :user="user"
    :avatar-options="avatarOptions"
    :can-edit="canEdit"
    :show-child-manager="showChildManager"
    :on-toggle-child-manager="toggleChildManager"
    :on-logout="handleLogout"
    :status="status"
    :status-tone="statusTone"
  >
    <ParentDashboard
      v-if="user.role === 'parent'"
      v-model:new-child-name="newChildName"
      v-model:new-child-pin="newChildPin"
      v-model:new-child-avatar-id="newChildAvatarId"
      v-model:editing-child-name="editingChildName"
      v-model:new-account-name="newAccountName"
      v-model:new-account-currency="newAccountCurrency"
      v-model:new-account-owner-id="newAccountOwnerId"
      v-model:show-account-creator="showAccountCreator"
      v-model:editing-account-name="editingAccountName"
      v-model:amount-input="amountInput"
      v-model:note-input="noteInput"
      v-model:transfer-amount="transferAmount"
      v-model:transfer-target-id="transferTargetId"
      v-model:transfer-note="transferNote"
      :show-child-manager="showChildManager"
      :child-users="childUsers"
      :child-avatars="childAvatars"
      :avatar-options="avatarOptions"
      :editing-child-id="editingChildId"
      :loading="loading"
      :sanitize-pin="sanitizePin"
      :on-create-child="handleCreateChild"
      :on-start-edit-child="startEditChild"
      :on-update-child="handleUpdateChild"
      :on-cancel-edit-child="cancelEditChild"
      :on-archive-child="handleArchiveChild"
      :currency-totals="currencyTotals"
      :format-amount="formatAmount"
      :selected-child-id="selectedChildId"
      :selected-child-name="selectedChild?.name ?? null"
      :on-select-child="selectChild"
      :selected-child-accounts="selectedChildAccounts"
      :selected-account-id="selectedAccountId"
      :balances="balances"
      :supported-currencies="supportedCurrencies"
      :editing-account-id="editingAccountId"
      :on-create-account="handleCreateAccount"
      :on-select-account="selectAccount"
      :on-start-edit-account="startEditAccount"
      :on-update-account="handleUpdateAccount"
      :on-cancel-edit-account="cancelEditAccount"
      :on-close-account="handleCloseAccount"
      :selected-account="selectedAccount"
      :can-edit="canEdit"
      :chart-points="chartPoints"
      :transfer-targets="transferTargets"
      :selected-account-balance="selectedAccountBalance"
      :paged-transactions="pagedTransactions"
      :has-more-transactions="hasMoreTransactions"
      :transaction-loading="transactionLoading"
      :transaction-labels="transactionLabels"
      :format-signed-amount="formatSignedAmount"
      :transaction-tone="transactionTone"
      :get-transaction-note="getTransactionNote"
      :format-timestamp="formatTimestamp"
      :on-add-transaction="handleAddTransaction"
      :on-transfer="handleTransfer"
      :on-load-more="handleLoadMoreForSelected"
      :on-void-transaction="handleVoidTransaction"
    />

    <ChildDashboard
      v-else
      :grouped-accounts="groupedAccounts"
      :selected-account-id="selectedAccountId"
      :selected-account="selectedAccount"
      :balances="balances"
      :format-amount="formatAmount"
      :on-select-account="selectAccount"
      :chart-points="chartPoints"
      :paged-transactions="pagedTransactions"
      :has-more-transactions="hasMoreTransactions"
      :transaction-loading="transactionLoading"
      :transaction-labels="transactionLabels"
      :format-signed-amount="formatSignedAmount"
      :transaction-tone="transactionTone"
      :get-transaction-note="getTransactionNote"
      :format-timestamp="formatTimestamp"
      :on-load-more="handleLoadMoreForSelected"
    />
  </AppShell>
</template>

<script setup lang="ts">
import { useLedgerApp } from "./app/useLedgerApp";
import AppShell from "./components/AppShell.vue";
import ChildDashboard from "./components/ChildDashboard.vue";
import LoginPage from "./components/LoginPage.vue";
import ParentDashboard from "./components/ParentDashboard.vue";

const {
  amountInput,
  avatarOptions,
  balances,
  canEdit,
  cancelEditAccount,
  cancelEditChild,
  chartPoints,
  childAvatars,
  childUsers,
  currencyTotals,
  editingAccountId,
  editingAccountName,
  editingChildId,
  editingChildName,
  formatAmount,
  formatSignedAmount,
  formatTimestamp,
  getTransactionNote,
  groupedAccounts,
  handleAddTransaction,
  handleArchiveChild,
  handleCloseAccount,
  handleCreateAccount,
  handleCreateChild,
  handleLoadMoreForSelected,
  handleLogin,
  handleLogout,
  handleTransfer,
  handleUpdateAccount,
  handleUpdateChild,
  handleVoidTransaction,
  hasMoreTransactions,
  isSupabaseConfigured,
  loading,
  loginPin,
  loginUsers,
  newAccountCurrency,
  newAccountName,
  newAccountOwnerId,
  newChildAvatarId,
  newChildName,
  newChildPin,
  noteInput,
  pagedTransactions,
  sanitizePin,
  selectAccount,
  selectChild,
  selectLoginUser,
  selectedAccount,
  selectedAccountBalance,
  selectedAccountId,
  selectedChild,
  selectedChildAccounts,
  selectedChildId,
  selectedLoginUser,
  selectedLoginUserId,
  sessionStatus,
  showAccountCreator,
  showChildManager,
  startEditAccount,
  startEditChild,
  status,
  statusTone,
  supportedCurrencies,
  toggleChildManager,
  transactionLabels,
  transactionLoading,
  transactionTone,
  transferAmount,
  transferNote,
  transferTargetId,
  transferTargets,
  user,
} = useLedgerApp();
</script>
